### ISSUE TITLE
Container image deployment to quay.io appears broken?

### ISSUE THREAD

**Issue by lwalter** [lunarway/humio_exporter#108]
Hi there!

Thanks for putting this solution together. My team would like to use this in our infrastructure to monitor our Humio clusters, however it appears that the container image deployment to quay.io hasn't received a new version in the last two years.

I'm checking the following: https://quay.io/repository/lunarway/humio_exporter?tab=tags&tag=latest

Additionally, the release tarballs do not contain any binaries so we cannot vendor them locally as well.

Would it be possible to get new versions deployed?

Thanks!

**Comment by EhsanLunar** [comment]
@lwalter 
This should now be solved, new releases will build new images and tag them with the release version and `latest`.
So the `latest` and `v0.2.12` is now available (`docker pull quay.io/lunarway/humio_exporter:v0.2.12`)

If you want/need the previous versions that wasn't being built, let us know
